export const MONACO = {
  OPTIONS: {
    fontSize: "22px",
    acceptSuggestionOnCommitCharacter: true,
    acceptSuggestionOnEnter: "on",
    accessibilitySupport: "auto",
    autoIndent: true,
    automaticLayout: true,
    codeLens: true,
    colorDecorators: true,
    contextmenu: true,
    cursorBlinking: "blink",
    cursorSmoothCaretAnimation: false,
    cursorStyle: "line",
    disableLayerHinting: false,
    disableMonospaceOptimizations: false,
    dragAndDrop: false,
    fixedOverflowWidgets: false,
    folding: true,
    foldingStrategy: "auto",
    fontLigatures: false,
    formatOnPaste: true,
    formatOnType: true,
    hideCursorInOverviewRuler: false,
    highlightActiveIndentGuide: true,
    links: true,
    mouseWheelZoom: false,
    multiCursorMergeOverlapping: true,
    multiCursorModifier: "alt",
    overviewRulerBorder: true,
    overviewRulerLanes: 2,
    quickSuggestions: true,
    quickSuggestionsDelay: 100,
    readOnly: false,
    renderControlCharacters: false,
    renderFinalNewline: true,
    renderIndentGuides: true,
    renderLineHighlight: "all",
    renderWhitespace: "none",
    revealHorizontalRightPadding: 30,
    roundedSelection: true,
    rulers: [],
    scrollBeyondLastColumn: 5,
    scrollBeyondLastLine: true,
    selectOnLineNumbers: true,
    selectionClipboard: true,
    selectionHighlight: true,
    showFoldingControls: "mouseover",
    smoothScrolling: false,
    suggestOnTriggerCharacters: true,
    wordBasedSuggestions: true,
    wordSeparators: "~!@#$%^&*()-=+[{]}|;:'\",.<>/?",
    wordWrap: "bounded",
    wordWrapBreakAfterCharacters: "\t})]?|&,;",
    wordWrapBreakBeforeCharacters: "{([+",
    wordWrapBreakObtrusiveCharacters: ".",
    wordWrapColumn: 80,
    wordWrapMinified: true,
    wrappingIndent: "none",
  },
  SUPPORTED_LANGUAGES: [
    { value: "c", label: "C", extension: ".c" },
    { value: "objective-c", label: "Objective-C", extension: ".m" },
    { value: "c++", label: "C++", extension: ".cpp" },
    { value: "python", label: "Python", extension: ".py" },
    { value: "java", label: "Java", extension: ".java" },
    { value: "c#", label: "C#", extension: ".cs" },
    {
      value: "javascript",
      label: "JavaScript",
      extension: ".js",
      codesnippet: 'console.log("Hello World")',
    },
    { value: "typescript", label: "TypeScript", extension: ".ts" },
    { value: "coffeescript", label: "CoffeeScript", extension: ".coffee" },
    { value: "json", label: "JSON", extension: ".json" },
    { value: "html", label: "HTML", extension: ".html" },
    { value: "css", label: "CSS", extension: ".css" },
    { value: "less", label: "LESS", extension: ".less" },
    { value: "sass", label: "SASS", extension: ".sass" },
    { value: "scss", label: "SCSS", extension: ".scss" },
    { value: "xml", label: "XML", extension: ".xml" },
    { value: "php", label: "PHP", extension: ".php" },
    { value: "razor", label: "Razor", extension: ".cshtml" },
    { value: "markdown", label: "Markdown", extension: ".md" },
    { value: "diff", label: "Diff", extension: ".diff" },
    { value: "vb", label: "VB", extension: ".vb" },
    { value: "batch", label: "Batch", extension: ".bat" },
    { value: "pug", label: "Pug", extension: ".pug" },
    { value: "f#", label: "F#", extension: ".fs" },
    { value: "lua", label: "Lua", extension: ".lua" },
    { value: "powershell", label: "Powershell", extension: ".ps1" },
    { value: "ruby", label: "Ruby", extension: ".rb" },
    { value: "r", label: "R", extension: ".r" },
  ],
  DEFAULT_LANGUAGE: {
    value: "javascript",
    label: "JavaScript",
    extension: ".js",
    codesnippet: 'console.log("Hello World")',
  },
};
